### ISSUE TITLE
Trying to instantiate streamingdataset from hydra/omegaconf causes error

### ISSUE THREAD

**Issue by mpetri** [mosaicml/streaming#409]
## To reproduce

create a simple dataloader config that you  then instantiate using hydra:

```
data:
  _target_: torch.utils.data.DataLoader
  batch_size: 30
  dataset:
    _target_:  streaming.StreamingDataset
    streams:
      -
          _target_: streaming.Stream
          remote: s3://bar/mds/
          proportion: 0.4
      -
          _target_: streaming.Stream
          remote: s3://foo/mds/
          proportion: 0.6
    epoch_size: 1000000
    shuffle: True
```

```
from hydra.utils import instantiate
from omegaconf import OmegaConf

cfg = OmegaConf.create(cfg_str)
dataloader = instantiate(cfg.data)
```

when trying to instantiate the object I get:

```
omegaconf.errors.KeyValidationError: ListConfig indices must be integers or slices, not "int64"
```

The problem specifically that the Sequence passed by OmegaConf/hydra is of type `ListConfig`:

here: https://github.com/omry/omegaconf/blob/master/omegaconf/listconfig.py#L84

where `omegaconf` requires indexes to be integers, however in your code the index is a int64, 

I'm not sure who is at fault here but a cast to `List[]` or the index to `int` would fix this.

## Expected behavior

Instantiating objects with hydra/omegaconf is standard. I would expect to be able to instantiate a streamingdataset with multiple streams correctly
